config/routes.rb
Rails.application.routes.draw do
  resources :articletypes

  mount Rich::Engine => '/rich', :as => 'rich'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  root 'home#index'

  scope '/admin' do
    resources :categories

    resources :tags

    resources :settings

    resources :images

    resources :posts

    resources :blogs
  end

  
 

end

app/controllers/articletyp_es_controller.rb
class ArticletypEsController < ApplicationController
  before_action :set_articletype, only: [:show, :edit, :update, :destroy]

  # GET /articletypes
  # GET /articletypes.json
  def index
    @articletypes = Articletype.all
  end

  # GET /articletypes/1
  # GET /articletypes/1.json
  def show
  end

  # GET /articletypes/new
  def new
    @articletype = Articletype.new
  end

  # GET /articletypes/1/edit
  def edit
  end

  # POST /articletypes
  # POST /articletypes.json
  def create
    @articletype = Articletype.new(articletype_params)

    respond_to do |format|
      if @articletype.save
        format.html { redirect_to @articletype, notice: 'Articletype was successfully created.' }
        format.json { render :show, status: :created, location: @articletype }
      else
        format.html { render :new }
        format.json { render json: @articletype.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articletypes/1
  # PATCH/PUT /articletypes/1.json
  def update
    respond_to do |format|
      if @articletype.update(articletype_params)
        format.html { redirect_to @articletype, notice: 'Articletype was successfully updated.' }
        format.json { render :show, status: :ok, location: @articletype }
      else
        format.html { render :edit }
        format.json { render json: @articletype.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articletypes/1
  # DELETE /articletypes/1.json
  def destroy
    @articletype.destroy
    respond_to do |format|
      format.html { redirect_to articletypes_url, notice: 'Articletype was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_articletype
      @articletype = Articletype.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def articletype_params
      params[:articletype]
    end
end

app/helpers/articletyp_es_helper.rb
module ArticletypEsHelper
end

app/views/articletyp_es/_form.html.haml
= form_for @articletype do |f|
  - if @articletype.errors.any?
    #error_explanation
      %h2= "#{pluralize(@articletype.errors.count, "error")} prohibited this articletype from being saved:"
      %ul
        - @articletype.errors.full_messages.each do |msg|
          %li= msg

  .actions
    = f.submit 'Save'

app/views/articletyp_es/edit.html.haml
%h1 Editing articletype

= render 'form'

= link_to 'Show', @articletype
\|
= link_to 'Back', articletypes_path

app/views/articletyp_es/index.html.haml
%h1 Listing articletypes

%table
  %thead
    %tr
      %th
      %th
      %th

  %tbody
    - @articletypes.each do |articletype|
      %tr
        %td= link_to 'Show', articletype
        %td= link_to 'Edit', edit_articletype_path(articletype)
        %td= link_to 'Destroy', articletype, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Articletype', new_articletype_path

app/views/articletyp_es/new.html.haml
%h1 New articletype

= render 'form'

= link_to 'Back', articletypes_path

app/views/articletyp_es/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_articletype_path(@articletype)
\|
= link_to 'Back', articletypes_path